lst=[1.5, "Python" ,-5, 4, 0.8, -3.2, 'C++']
lst.append(0.8)
print("Aftre Appending 0.8")
print(lst)
add= [4,1.5,6,0.8]
lst.append(add)
print("Aftre Appending list add ")
print(lst)
lst1=[1.5, "Python" ,-5, 4, 0.8, -3.2, 'C++']
lst1.insert(2,20)
print("Aftre Adding element at second position ")
print(lst1)
lst1.remove('C++')
print("Aftre removing C++")
print(lst1)
lst1.pop(5)
print("Aftre removing element at 5th position ")
print(lst1)
pos= lst1.index(-5)
print("Position of element of -5 ")
print(pos)
ct=lst1.count(4)
print("Occurences of element 4 ")
print(ct)
print("List from 2 to 6 position ")
print(lst1[2:6])
lst1.reverse()
print("print list aftre reversing ")
print(lst1)
copy=lst1 ## copy the list
print("Aftre copying list lst1 wieh copy ")
print(copy)
