population=int(input("Enter Population:"))
noOfMen=0.52*population
noOfWomen=population-noOfMen
noOfIlliterate=0.48*population
print("Total Illiteracy=",noOfIlliterate)
noOfLitMen=0.35*population
noOfIllitMen=noOfMen-noOfLitMen
noOfIllitWomen=noOfIlliterate-noOfIllitMen
print("Total Illiterate Men=",noOfIllitMen)
print("Total Illiterate Women=",noOfIllitWomen)